### ISSUE TITLE
failure to install particles

### ISSUE THREAD

**Issue by PaulLantos** [thomasp85/particles#3]
I get the following when I try to install particles. Any suggestions? Thanks.

* installing *source* package 'particles' ...
** libs
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11 -I"C:/PROGRA~1/MICROS~3/ROPEN~1/R-34~1.2/include" -DNDEBUG  -I"C:/Users/pl39/Documents/R/win-library/3.4/Rcpp/include"   -I"C:/swarm/workspace/External-R-3.4.2/vendor/extsoft/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11 -I"C:/PROGRA~1/MICROS~3/ROPEN~1/R-34~1.2/include" -DNDEBUG  -I"C:/Users/pl39/Documents/R/win-library/3.4/Rcpp/include"   -I"C:/swarm/workspace/External-R-3.4.2/vendor/extsoft/include"     -O2 -Wall  -mtune=core2 -c collision.cpp -o collision.o
collision.cpp: In function 'Rcpp::NumericMatrix collision(Rcpp::NumericMatrix, Rcpp::NumericMatrix, Rcpp::NumericVector, double)':
collision.cpp:13:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (i = 0; i < pos.nrow(); ++i) {
                 ^
collision.cpp:26:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (i = 0; i < pos.nrow(); ++i) {
                 ^
collision.cpp:29:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (i = 0; i < pos.nrow(); ++i) {
                 ^
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11 -I"C:/PROGRA~1/MICROS~3/ROPEN~1/R-34~1.2/include" -DNDEBUG  -I"C:/Users/pl39/Documents/R/win-library/3.4/Rcpp/include"   -I"C:/swarm/workspace/External-R-3.4.2/vendor/extsoft/include"     -O2 -Wall  -mtune=core2 -c nbody.cpp -o nbody.o
nbody.cpp: In function 'Rcpp::NumericMatrix nbody(Rcpp::NumericMatrix, Rcpp::NumericVector, double, double, double, double)':
nbody.cpp:13:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (i = 0; i < pos.nrow(); ++i) {
                 ^
nbody.cpp:23:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (i = 0; i < pos.nrow(); ++i) {
                 ^
nbody.cpp:26:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (i = 0; i < pos.nrow(); ++i) {
                 ^
c:/Rtools/mingw_64/bin/g++ -m64 -std=gnu++11 -I"C:/PROGRA~1/MICROS~3/ROPEN~1/R-34~1.2/include" -DNDEBUG  -I"C:/Users/pl39/Documents/R/win-library/3.4/Rcpp/include"   -I"C:/swarm/workspace/External-R-3.4.2/vendor/extsoft/include"     -O2 -Wall  -mtune=core2 -c pathdist.cpp -o pathdist.o
c:/Rtools/mingw_64/bin/g++ -m64 -shared -s -static-libgcc -o particles.dll tmp.def RcppExports.o collision.o nbody.o pathdist.o -LC:/swarm/workspace/External-R-3.4.2/vendor/extsoft/lib/x64 -LC:/swarm/workspace/External-R-3.4.2/vendor/extsoft/lib -LC:/PROGRA~1/MICROS~3/ROPEN~1/R-34~1.2/bin/x64 -lR
installing to C:/Users/pl39/Documents/R/win-library/3.4/particles/libs/x64
** R
** preparing package for lazy loading
Error : object 'graph_is_dag' is not exported by 'namespace:tidygraph'
ERROR: lazy loading failed for package 'particles'
* removing 'C:/Users/pl39/Documents/R/win-library/3.4/particles'
Installation failed: Command failed (1)

**Comment by thomasp85** [comment]
You’ll need to update tidygraph

**Comment by PaulLantos** [comment]
Thanks!
Paul
_____________________________________________
Paul M. Lantos, MD, MS GIS, FIDSA, FAAP, FACP
Associate Professor of Internal Medicine and Pediatrics
  Pediatric Infectious Diseases
  General Internal Medicine
Duke University School of Medicine
Duke Global Health Institute
_____________________________________________
